### ISSUE TITLE
error in main_model_params

### ISSUE THREAD

**Issue by whubaichuan** [loeweX/Forward-Forward#6]
hi, nice work. 

The optimizer for the main model seems to be wrong. The code in this [file](https://github.com/loeweX/Forward-Forward/blob/main/src/utils.py): 

` if all(p is not x for x in model.classification_loss.parameters())` but `model.classification_loss.parameters()` is empty. Thus, I guess the code should be changed to: `if all(p is not x for x in model.linear_classifier.parameters())` ?

**Comment by loeweX** [comment]
Good catch, thank you for pointing this out! 

Would you like to open a pull request with the necessary changes? I believe [line 45](https://github.com/loeweX/Forward-Forward/blob/92c0c1c0565063dae0121734075013cab20da5c5/src/utils.py#L45C37-L45C46) would need to be changed accordingly.

**Comment by whubaichuan** [comment]
@loeweX Hi, thanks for your quick reply. I will do it soon.
